include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = biolockprefs

biolockprefs_FILES = BLPRootListController.m
biolockprefs_FRAMEWORKS = UIKit
biolockprefs_PRIVATE_FRAMEWORKS = Preferences
biolockprefs_INSTALL_PATH = /Library/PreferenceBundles
biolockprefs_CFLAGS = -fobjc-arc
biolockprefs_EXTRA_FRAMEWORKS = AltList

include $(THEOS_MAKE_PATH)/bundle.mk
